name: Trigger Sample

on: 
  workflow_dispatch:
    inputs:
      os:
        description: OS
        type: choice
        default: 'ubuntu'
        options: 
          - windows
          - ubuntu

concurrency:
  group: ${{ github.workflow }}-${{ inputs.os }}

run-name: Run trigger for OS ${{ inputs.os }}

env:
  GO_VERSION: '1.21.x'
  GOPRIVATE: 'github.com/pratikpanchal4472/*'
  CICD_TOKEN: ${{secrets.CICD_TOKEN}}
  ACTOR: ${{github.actor}}

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Go Composite
        uses: ./.github/actions/go
        with:
          os: ${{ inputs.os }}
          goprivate: ${{ env.GOPRIVATE }}
  
  job2:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Print hello job2 but fails with exit code 1
        run: echo "Hello Job2" && exit 1
      
  job3:
    name: Job 3 executes after job2 but always if job2 fails.
    runs-on: ubuntu-latest
    if: always()
    needs: 
      - init
      - job2
    steps:
      - name: Print My job
        run: echo "Hello job3"
