run:
  tests: true
  timeout: "5m"
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs-use-default: true

linters-settings:
  goimports:
    local-prefixes: github.com/pratikpanchal4472

  gofumpt:
    extra-rules: false

linters:
  disable-all: true
  deadline: "5m"
  enable:
    - staticcheck
    - govet
    - gofmt
    - goimports
    - gosec
    - misspell
    - gofumpt